name: Test
on:
  pull_request:
    branches:
      - master

jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command:
          - compile
    steps:
      - uses: actions/checkout@v2
      - name: Run 'make ${{ matrix.command }}'
        run: make ${{ matrix.command }}
